<a href="https://colab.research.google.com/github/Son-github/DeepLearning_PyTroch-1/blob/main/%08DeepLearning_with_PyTorch_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PyTorch 사용법**

1) 1D with Numpy

In [1]:
import numpy as np

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


In [4]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1])

t[0] t[1] t[-1] =  0.0 1.0 6.0


In [8]:
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1]) # 주의할 점은 슬라이싱은 [시작 번호 : 끝 번호]라고 했을 때, 끝 번호에 해당하는 것은 포함하지 않음
# 여기서 마지막까지 나오게 하고 싶다면 t[4:] 이렇게 쓰면 됌

t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]


2) 2D with Numpy

In [9]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [10]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  2
Shape of t:  (4, 3)


3) 파이토치 텐서 선언하기(PyTorch Tensor Allocation)

In [11]:
import torch

1) 1D with PyTorch

In [12]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [13]:
print(t.dim()) # rank, 즉, 차원
print(t.shape) # shape
print(t.size()) # shape

1
torch.Size([7])
torch.Size([7])


In [14]:
print(t[0], t[1], t[-1]) # 인덱스로 접근
print(t[2:5], t[4:-1]) # 슬라이싱
print(t[:2], t[3:]) # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


2) 2D with PyTorch

In [16]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [17]:
print(t.dim()) # rank. 즉, 차원
print(t.size()) # shape

2
torch.Size([4, 3])


In [18]:
print(t[:, 1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져옴.
print(t[:, 1].size()) # ↑ 위의 경우의 크기

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [19]:
print(t[:, :-1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원에서는 맨 만지막에서 첫번째를 제외하고 다 가져옴.

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [27]:
print(t[:2,:2]) # 첫번째는 몇 개의 행을 가져올 것인지, 두번째는 몇 개의 열을 가져올 것인지 나타냄

tensor([[1., 2.],
        [4., 5.]])


3) 브로드캐스팅(Broadcasting)

In [28]:
m1 = torch.FloatTensor([3, 3])
m2 = torch.FloatTensor([2, 2])
print(m1 + m2)

tensor([5., 5.])


In [29]:
m1 = torch.FloatTensor([3, 3])
m2 = torch.FloatTensor([2])
print(m1 + m2)

tensor([5., 5.])


In [30]:
m1 = torch.FloatTensor([3, 3])
m2 = torch.FloatTensor([[2], [3]])
print(m1 + m2)

tensor([[5., 5.],
        [6., 6.]])


In [31]:
'''
브로드캐스팅 과정에서 실제로 두 텐서가 어떻게 변경되는지 보겠습니다.
[1, 2]
==> [[1, 2],
     [1, 2]]
[3]
[4]
==> [[3, 3],
     [4, 4]]
'''

'\n브로드캐스팅 과정에서 실제로 두 텐서가 어떻게 변경되는지 보겠습니다.\n[1, 2]\n==> [[1, 2],\n     [1, 2]]\n[3]\n[4]\n==> [[3, 3],\n     [4, 4]]\n'

4) 자주 사용되는 기능들

In [33]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of matrix 2: ', m2.shape)
print(m1.matmul(m2)) # 행렬의 곱셈

Shape of Matrix 1:  torch.Size([2, 2])
Shape of matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [34]:
print(m1 * m2)
print(m1.mul(m2)) # m2가 브로드캐스팅 된 후 곱해짐

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [35]:
'''
브로드캐스팅 과정에서 m2 텐서가 어떻게 변경되는지 보겠습니다.
[1]
[2]
==> [[1, 1],
     [2, 2]]
'''

'\n브로드캐스팅 과정에서 m2 텐서가 어떻게 변경되는지 보겠습니다.\n[1]\n[2]\n==> [[1, 1],\n     [2, 2]]\n'

In [36]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [37]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [39]:
print(t.mean())
print(t.mean(dim=0))

tensor(2.5000)
tensor([2., 3.])


In [40]:
'''
실제 연산 과정
t.mean(dim=0)은 입력에서 첫번째 차원을 제거한다.

[[1., 2.],
 [3., 4.]]

1과 3의 평균을 구하고, 2와 4의 평균을 구한다.
결과 ==> [2., 3.]
'''

'\n실제 연산 과정\nt.mean(dim=0)은 입력에서 첫번째 차원을 제거한다.\n\n[[1., 2.],\n [3., 4.]]\n\n1과 3의 평균을 구하고, 2와 4의 평균을 구한다.\n결과 ==> [2., 3.]\n'

In [42]:
print(t.mean(dim=1))
'''실제 연산 결과는 (2 × 1)
[1. 5]
[3. 5]'''

tensor([1.5000, 3.5000])


'실제 연산 결과는 (2 × 1)\n[1. 5]\n[3. 5]'

In [43]:
print(t.mean(dim=-1)) # 마지막 차원을 제거한다는 의미

tensor([1.5000, 3.5000])


In [44]:
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [45]:
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거(열을 덧셈)
print(t.sum(dim=1)) # 열을 제거(행을 덧셈)
print(t.sum(dim=-1)) #열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [46]:
print(t.max())

tensor(4.)


In [47]:
print(t.max(dim=0)) # Returns two values: max and argmax

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [48]:
'''
[1, 1]가 무슨 의미인지 봅시다. 기존 행렬을 다시 상기해봅시다.
[[1, 2],
 [3, 4]]
첫번째 열에서 0번 인덱스는 1, 1번 인덱스는 3입니다.
두번째 열에서 0번 인덱스는 2, 1번 인덱스는 4입니다.
다시 말해 3과 4의 인덱스는 [1, 1]입니다.
'''

'\n[1, 1]가 무슨 의미인지 봅시다. 기존 행렬을 다시 상기해봅시다.\n[[1, 2],\n [3, 4]]\n첫번째 열에서 0번 인덱스는 1, 1번 인덱스는 3입니다.\n두번째 열에서 0번 인덱스는 2, 1번 인덱스는 4입니다.\n다시 말해 3과 4의 인덱스는 [1, 1]입니다.\n'

In [59]:
t = torch.FloatTensor([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
print(t)
print(t[:2, :2, :1])

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
tensor([[[0.],
         [3.]],

        [[6.],
         [9.]]])


In [51]:
print(t.shape)

torch.Size([2, 2, 3])


In [52]:
print(t.view([-1, 3])) # t라는 텐서를 (?, 3)의 크기로 변경
# -1은 첫번째 차원은 사용자가 잘 모르고, 3은 두번째 차원의 길이는 3을 가지도록 하라는 의미 => 현재 3차원 텐서를 2차원 텐서로 변경하되 (?,3)형태로 변환하라는 뜻.
print(t.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [60]:
print(t.view([-1, 1, 3]))

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])


In [61]:
f = torch.FloatTensor([[0], [1], [2]])
print(f)
print(f.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [63]:
print(f.squeeze()) # Squeeze는 차원이 1인 경우, 해당 차원을 제거
print(f.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [64]:
f = torch.FloatTensor([0, 1, 2])
print(f.shape)

torch.Size([3])


In [67]:
print(f.unsqueeze(0)) # 특정 위치에 1인 차원을 추가, 첫번째 차원의 인덱스를 의미하는 숫자 0을 인자로 넣으면 첫번째 차원에 1인 차원이 추가
print(f.unsqueeze(0).shape)
print(f.view([1,-1]))
print(f.view([1,-1]).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [68]:
print(f.unsqueeze(1)) # 특정 위치에 1인 차원을 추가, 두번째 차원에 1을 추가하겠다는 것을 의미
print(f.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [70]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
print(lt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [71]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [72]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [73]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
print(torch.cat([x, y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [75]:
print(torch.cat([x, y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [76]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [77]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [78]:
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [79]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [80]:
print(torch.ones_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기
print(torch.zeros_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 0으로 채우기

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [81]:
x = torch.FloatTensor([[1, 2], [3, 4]])

print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [83]:
print(x.mul_(2.)) # _를 mul뒤에 쓰면 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x)

tensor([[ 4.,  8.],
        [12., 16.]])
tensor([[ 4.,  8.],
        [12., 16.]])
